title: Jaeho Choi
description: Jaeho Choi, Ph.D. student in Economics at Sogang University
baseurl: "/Homepage"
url: "https://nachoidot.github.io"
markdown: kramdown
timezone: Asia/Seoul
theme: null
exclude:
  - cv.tex
